# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_StemFilter(object):
    def setupUi(self, StemFilter):
        StemFilter.setObjectName(_fromUtf8("StemFilter"))
        StemFilter.resize(442, 684)
        font = QtGui.QFont()
        font.setPointSize(9)
        StemFilter.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Projects/Old Projects/Name_Checker/Files/UI/lamp.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StemFilter.setWindowIcon(icon)
        StemFilter.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(StemFilter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.names_text = QtGui.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.names_text.setFont(font)
        self.names_text.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.names_text.setObjectName(_fromUtf8("names_text"))
        self.verticalLayout_2.addWidget(self.names_text)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ignore_line = QtGui.QLineEdit(self.centralwidget)
        self.ignore_line.setObjectName(_fromUtf8("ignore_line"))
        self.verticalLayout.addWidget(self.ignore_line)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.get_stems_btn = QtGui.QPushButton(self.centralwidget)
        self.get_stems_btn.setObjectName(_fromUtf8("get_stems_btn"))
        self.horizontalLayout_3.addWidget(self.get_stems_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.close_btn = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName(_fromUtf8("close_btn"))
        self.horizontalLayout_2.addWidget(self.close_btn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        StemFilter.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(StemFilter)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        StemFilter.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(StemFilter)
        self.actionExit.setShortcut(_fromUtf8(""))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionView_pharma_avoids = QtGui.QAction(StemFilter)
        self.actionView_pharma_avoids.setObjectName(_fromUtf8("actionView_pharma_avoids"))
        self.actionView_inn_avoids = QtGui.QAction(StemFilter)
        self.actionView_inn_avoids.setObjectName(_fromUtf8("actionView_inn_avoids"))
        self.actionProject_avoids = QtGui.QAction(StemFilter)
        self.actionProject_avoids.setObjectName(_fromUtf8("actionProject_avoids"))
        self.actionInternal_names = QtGui.QAction(StemFilter)
        self.actionInternal_names.setObjectName(_fromUtf8("actionInternal_names"))
        self.actionPresented_names = QtGui.QAction(StemFilter)
        self.actionPresented_names.setObjectName(_fromUtf8("actionPresented_names"))
        self.actionCompetitor_names = QtGui.QAction(StemFilter)
        self.actionCompetitor_names.setObjectName(_fromUtf8("actionCompetitor_names"))
        self.actionOptions = QtGui.QAction(StemFilter)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionTool_1 = QtGui.QAction(StemFilter)
        self.actionTool_1.setObjectName(_fromUtf8("actionTool_1"))
        self.actionTool_style = QtGui.QAction(StemFilter)
        self.actionTool_style.setObjectName(_fromUtf8("actionTool_style"))
        self.actionTool_3 = QtGui.QAction(StemFilter)
        self.actionTool_3.setObjectName(_fromUtf8("actionTool_3"))
        self.actionTool_4 = QtGui.QAction(StemFilter)
        self.actionTool_4.setObjectName(_fromUtf8("actionTool_4"))
        self.actionTool_5 = QtGui.QAction(StemFilter)
        self.actionTool_5.setObjectName(_fromUtf8("actionTool_5"))
        self.actionCommit_names = QtGui.QAction(StemFilter)
        self.actionCommit_names.setObjectName(_fromUtf8("actionCommit_names"))
        self.actionSort_names = QtGui.QAction(StemFilter)
        self.actionSort_names.setObjectName(_fromUtf8("actionSort_names"))
        self.actionFind_conflicts = QtGui.QAction(StemFilter)
        self.actionFind_conflicts.setObjectName(_fromUtf8("actionFind_conflicts"))
        self.actionClear_avoids = QtGui.QAction(StemFilter)
        self.actionClear_avoids.setObjectName(_fromUtf8("actionClear_avoids"))
        self.actionView_stripped_names = QtGui.QAction(StemFilter)
        self.actionView_stripped_names.setObjectName(_fromUtf8("actionView_stripped_names"))
        self.actionINN_avoids_password_required = QtGui.QAction(StemFilter)
        self.actionINN_avoids_password_required.setObjectName(_fromUtf8("actionINN_avoids_password_required"))
        self.actionPharma_Avoids_password_req = QtGui.QAction(StemFilter)
        self.actionPharma_Avoids_password_req.setObjectName(_fromUtf8("actionPharma_Avoids_password_req"))
        self.actionINN_avoids = QtGui.QAction(StemFilter)
        self.actionINN_avoids.setObjectName(_fromUtf8("actionINN_avoids"))
        self.actionPharma_avoids = QtGui.QAction(StemFilter)
        self.actionPharma_avoids.setObjectName(_fromUtf8("actionPharma_avoids"))
        self.actionAdd_avoids = QtGui.QAction(StemFilter)
        self.actionAdd_avoids.setObjectName(_fromUtf8("actionAdd_avoids"))

        self.retranslateUi(StemFilter)
        QtCore.QMetaObject.connectSlotsByName(StemFilter)

    def retranslateUi(self, StemFilter):
        StemFilter.setWindowTitle(_translate("StemFilter", "PM Stem Filter", None))
        self.label_2.setText(_translate("StemFilter", "Enter Names Here", None))
        self.names_text.setStatusTip(_translate("StemFilter", "Enter names here", None))
        self.ignore_line.setStatusTip(_translate("StemFilter", "Enter a stem to ignore", None))
        self.ignore_line.setPlaceholderText(_translate("StemFilter", "Enter a stem to ignore...", None))
        self.get_stems_btn.setStatusTip(_translate("StemFilter", "Build an excel document showing INN conflicts", None))
        self.get_stems_btn.setText(_translate("StemFilter", "Get INN Avoids\nThis will build and open a new excel document", None))
        self.close_btn.setStatusTip(_translate("StemFilter", "Close this application", None))
        self.close_btn.setText(_translate("StemFilter", "Close", None))
        self.close_btn.setShortcut(_translate("StemFilter", "Esc", None))
        self.actionExit.setText(_translate("StemFilter", "Leave", None))
        self.actionView_pharma_avoids.setText(_translate("StemFilter", "View Pharma Avoids", None))
        self.actionView_pharma_avoids.setStatusTip(_translate("StemFilter", "View Pharma Avoids", None))
        self.actionView_inn_avoids.setText(_translate("StemFilter", "View INN Avoids", None))
        self.actionProject_avoids.setText(_translate("StemFilter", "Project Avoids", None))
        self.actionInternal_names.setText(_translate("StemFilter", "Internal Names", None))
        self.actionPresented_names.setText(_translate("StemFilter", "Presented Names", None))
        self.actionCompetitor_names.setText(_translate("StemFilter", "Competitor Names", None))
        self.actionOptions.setText(_translate("StemFilter", "Options", None))
        self.actionOptions.setStatusTip(_translate("StemFilter", "View Options", None))
        self.actionTool_1.setText(_translate("StemFilter", "Tool 1", None))
        self.actionTool_style.setText(_translate("StemFilter", "Tool 2", None))
        self.actionTool_3.setText(_translate("StemFilter", "Tool 3", None))
        self.actionTool_4.setText(_translate("StemFilter", "Tool 4", None))
        self.actionTool_5.setText(_translate("StemFilter", "Tool 5", None))
        self.actionCommit_names.setText(_translate("StemFilter", "Commit Names", None))
        self.actionSort_names.setText(_translate("StemFilter", "Sort Names (A-Z)", None))
        self.actionFind_conflicts.setText(_translate("StemFilter", "Find Conflicts", None))
        self.actionClear_avoids.setText(_translate("StemFilter", "Clear All Avoids", None))
        self.actionView_stripped_names.setText(_translate("StemFilter", "View names without rationale", None))
        self.actionINN_avoids_password_required.setText(_translate("StemFilter", "INN avoids (password req.)", None))
        self.actionPharma_Avoids_password_req.setText(_translate("StemFilter", "Pharma Avoids (password req.)", None))
        self.actionINN_avoids.setText(_translate("StemFilter", "INN Avoids", None))
        self.actionPharma_avoids.setText(_translate("StemFilter", "Pharma Avoids", None))
        self.actionAdd_avoids.setText(_translate("StemFilter", "Add Avoids", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    StemFilter = QtGui.QMainWindow()
    ui = Ui_StemFilter()
    ui.setupUi(StemFilter)
    StemFilter.show()
    sys.exit(app.exec_())
